### ISSUE TITLE
Unmentioned required libraries?

### ISSUE THREAD

**Issue by DuendeInexistente** [loot/loot#1344]
Hey, I'm trying to build this in ubuntu 20 and had to install a couple requirements not listed in the readme to get the build to (Sort of) function.  Specifically ``libssh2-1-dev``, ``libhttp-parser-dev``, ``libicu-dev`` and ``libboost-locale1.71-dev``. CMake detected libboost and ``libicu-dev`` being missing, and after that when runnning make itself ld threw cryptic errors because the others were missing.
Then I get past that, and...
```
[ 61%] Linking CXX executable loot_gui_tests
/usr/bin/ld: warning: libssl.so.1.0.0, needed by /home/cammera/Downloads/falloutNV/loot/build/external/src/libloot/libloot.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libcrypto.so.1.0.0, needed by /home/cammera/Downloads/falloutNV/loot/build/external/src/libloot/libloot.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libicuuc.so.55, needed by /home/cammera/Downloads/falloutNV/loot/build/external/src/libloot/libloot.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: /home/cammera/Downloads/falloutNV/loot/build/external/src/libloot/libloot.so: undefined reference to `SSL_CTX_new@OPENSSL_1.0.0'
...(Goes on for way longer)
```
So I ran ldd on libloot.
```
	linux-vdso.so.1 (0x00007ffc54d8e000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007ff106725000)
	libssl.so.1.0.0 => not found
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007ff106709000)
	libcrypto.so.1.0.0 => not found
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007ff1066fe000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007ff1066db000)
	libicuuc.so.55 => not found
	libssh2.so.1 => /lib/x86_64-linux-gnu/libssh2.so.1 (0x00007ff1066aa000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007ff1064c9000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007ff10637a000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007ff10635f000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ff10616d000)
	/lib64/ld-linux-x86-64.so.2 (0x00007ff107693000)
	libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007ff10604d000)
	libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007ff10602a000)
```
Right off the bat: Libcuuc (Libicu 55) isn't available in ubuntu 20, only libicu66, and the only package that provided the libssl and libcrypto files (nsight-compute, something about nvidia profiling, and before anyone asks I do have libssl and libcrypto; The repo has ssl 1.1, though) didn't fix the issue. Am I missing some package I should know about or is the code not up to date with libraries?

**Comment by Ortham** [comment]
The code builds on the Ubuntu 18.04-based GitHub Actions environment, and previously built on Travis CI's Ubuntu 18.04 environment, I've made no attempt to get it to build on other environments though.

You probably need to build libloot yourself on Ubuntu 20.04 so that it links to the libraries you have, instead of using the prebuilt binary that was built on GitHub Actions / Travis CI. You can then point to that binary when building LOOT itself.

**Comment by Ortham** [comment]
LOOT's CI builds use Ubuntu 20.04 as of f29997039983cd48b5eba7a3002f28ea82e16fdc, so I'm closing this as the libraries mentioned above no longer cause issues.

**Comment by oblende** [comment]
You should probably reopen this bug. It's back but this time Ubuntu 20.10 is using libicu67 now.

`/usr/bin/ld: warning: libicuuc.so.66, needed by external/src/libloot/libloot.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: external/src/libloot/libloot.so: undefined reference to `icu_66::UnicodeString::fromUTF8(icu_66::StringPiece)'
/usr/bin/ld: external/src/libloot/libloot.so: undefined reference to `icu_66::UnicodeString::foldCase(unsigned int)'
/usr/bin/ld: external/src/libloot/libloot.so: undefined reference to `icu_66::UnicodeString::doCaseCompare(int, int, char16_t const*, int, int, unsigned int) const'
/usr/bin/ld: external/src/libloot/libloot.so: undefined reference to `icu_66::ByteSink::~ByteSink()'
/usr/bin/ld: external/src/libloot/libloot.so: undefined reference to `icu_66::UnicodeString::~UnicodeString()'
/usr/bin/ld: external/src/libloot/libloot.so: undefined reference to `icu_66::UnicodeString::toUTF8(icu_66::ByteSink&) const'
/usr/bin/ld: external/src/libloot/libloot.so: undefined reference to `icu_66::ByteSink::Flush()'
/usr/bin/ld: external/src/libloot/libloot.so: undefined reference to `vtable for icu_66::ByteSink'
/usr/bin/ld: external/src/libloot/libloot.so: undefined reference to `icu_66::UMemory::operator delete(void*)'
/usr/bin/ld: external/src/libloot/libloot.so: undefined reference to `typeinfo for icu_66::ByteSink'
/usr/bin/ld: external/src/libloot/libloot.so: undefined reference to `icu_66::ByteSink::GetAppendBuffer(int, int, char*, int, int*)'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/loot_gui_tests.dir/build.make:343: loot_gui_tests] Error 1
make[1]: *** [CMakeFiles/Makefile2:119: CMakeFiles/loot_gui_tests.dir/all] Error 2
make: *** [Makefile:103: all] Error 2
`

**Comment by Ortham** [comment]
It's not a bug to depend on specific versions of libraries that don't happen to be provided by your OS's package manager: there is no "fix" that I can provide for that. If I got it working for Ubuntu 21.10 it would break for 20.04 (and other versions). Either build libloot from source to link it to the libicu you have installed, or build libicu 66 so that it's available for linking.
